# Generated by Django 5.2.15 on 2026-07-05 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='studentscore',
            new_name='scores_stud_registr_a03e8d_idx',
            old_name='scores_stud_regist_6a2b4d_idx',
        ),
        migrations.RenameIndex(
            model_name='studentscore',
            new_name='scores_stud_math_b4a042_idx',
            old_name='scores_stud_math_3d5e68_idx',
        ),
        migrations.RenameIndex(
            model_name='studentscore',
            new_name='scores_stud_literat_6ddd81_idx',
            old_name='scores_stud_literat_3ed1a8_idx',
        ),
        migrations.RenameIndex(
            model_name='studentscore',
            new_name='scores_stud_foreign_5311d4_idx',
            old_name='scores_stud_foreign_8d0be0_idx',
        ),
        migrations.RenameIndex(
            model_name='studentscore',
            new_name='scores_stud_physics_67a0ad_idx',
            old_name='scores_stud_physics_4c56f0_idx',
        ),
        migrations.RenameIndex(
            model_name='studentscore',
            new_name='scores_stud_chemist_a2c82a_idx',
            old_name='scores_stud_chemist_6f2e1f_idx',
        ),
        migrations.RenameIndex(
            model_name='studentscore',
            new_name='scores_stud_biology_f93743_idx',
            old_name='scores_stud_biology_4a6d4c_idx',
        ),
        migrations.RenameIndex(
            model_name='studentscore',
            new_name='scores_stud_history_6b6fb7_idx',
            old_name='scores_stud_history_8a1f61_idx',
        ),
        migrations.RenameIndex(
            model_name='studentscore',
            new_name='scores_stud_geograp_40c06a_idx',
            old_name='scores_stud_geograph_ae0f29_idx',
        ),
        migrations.RenameIndex(
            model_name='studentscore',
            new_name='scores_stud_civic_e_e06187_idx',
            old_name='scores_stud_civic_e_3bf721_idx',
        ),
    ]
