# Generated by Django 5.2.15 on 2026-07-05 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_remove_subject_indexes'),
        ('scores', '0002_rename_scores_stud_regist_6a2b4d_idx_scores_stud_registr_a03e8d_idx_and_more'),
    ]

    operations = [
    ]
