# Generated by Django 5.2.15 on 2026-07-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0003_merge_20260705_1612'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='studentscore',
            name='scores_stud_registr_a03e8d_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentscore',
            name='scores_stud_math_b4a042_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentscore',
            name='scores_stud_literat_6ddd81_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentscore',
            name='scores_stud_foreign_5311d4_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentscore',
            name='scores_stud_physics_67a0ad_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentscore',
            name='scores_stud_chemist_a2c82a_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentscore',
            name='scores_stud_biology_f93743_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentscore',
            name='scores_stud_history_6b6fb7_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentscore',
            name='scores_stud_geograp_40c06a_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentscore',
            name='scores_stud_civic_e_e06187_idx',
        ),
        migrations.AlterField(
            model_name='studentscore',
            name='biology',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='studentscore',
            name='chemistry',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='studentscore',
            name='civic_education',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='studentscore',
            name='foreign_language',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='studentscore',
            name='geography',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='studentscore',
            name='history',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='studentscore',
            name='literature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='studentscore',
            name='math',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='studentscore',
            name='physics',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
